version: 2

project_name: nais-cli

before:
  hooks:
    - go mod tidy

builds:
  - env: [ CGO_ENABLED=0 ]
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    id: nais-other
    dir: .
    main: ./
    binary: nais
    ldflags:
      - -s -w -X github.com/nais/cli/cmd.version={{.Version}} -X github.com/nais/cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/nais/cli/pkg/metrics.version={{.Version}}
  - env: [ CGO_ENABLED=0 ]
    targets:
      - windows_amd64
    id: nais-windows
    dir: .
    main: ./
    binary: nais
    ldflags:
      - -s -w -X github.com/nais/cli/cmd.version={{.Version}} -X github.com/nais/cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/nais/cli/pkg/metrics.version={{.Version}}
    hooks:
      post:
        - osslsigncode sign -certs nais.crt -key nais.key -n "nais-cli" -i "https://doc.nais.io/cli" -verbose -in "{{ .Path }}" -out "{{ .Path }}-signed"
        - mv "{{ .Path }}-signed" "{{ .Path }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: nais
    name: cli
  header: |
    ## nais-cli ({{ .Version }})

brews:
  - repository:
      owner: nais
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_PUSH_TOKEN }}"
    name: nais
    homepage: "https://github.com/nais/cli"
    description: "Command-line interface for NAIS"
    directory: Formula
    install: |
      bin.install "nais"
    test: |
      assert_match version, shell_output("#{bin}/nais version")

nfpms:
  - package_name: nais
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    vendor: NAV / nais team
    homepage: "https://github.com/nais/cli"
    maintainer: NAV / nais team
    description: "Command-line interface for NAIS"
    license: MIT
    formats:
      - deb
    version_metadata: git

scoops:
  - repository:
      owner: nais
      name: scoop-bucket
      token: "{{ .Env.SCOOP_PUSH_TOKEN }}"
    homepage: "https://github.com/nais/cli"
    description: "Command-line interface for NAIS"
    license: MIT
