version: 2

project_name: nais-cli

before:
  hooks:
    - go mod tidy
    - ./script/completions.sh

archives:
  - files:
      - README.md
      - LICENSE
      - completions/*

builds:
  - env: [CGO_ENABLED=0]
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    id: nais-other
    dir: .
    main: ./
    binary: nais
    ldflags:
      - -s -w -X github.com/nais/cli/internal/version.Version={{.Version}} -X github.com/nais/cli/internal/version.Commit={{.Commit}}
  - env: [CGO_ENABLED=0]
    targets:
      - windows_amd64
    id: nais-windows
    dir: .
    main: ./
    binary: nais
    ldflags:
      - -s -w -X github.com/nais/cli/internal/version.Version={{.Version}} -X github.com/nais/cli/internal/version.Commit={{.Commit}}
    hooks:
      post:
        - osslsigncode sign -certs nais.crt -key nais.key -n "nais-cli" -i "https://doc.nais.io/cli" -verbose -in "{{ .Path }}" -out "{{ .Path }}-signed"
        - mv "{{ .Path }}-signed" "{{ .Path }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: nais
    name: cli
  header: |
    ## nais-cli ({{ .Version }})

brews:
  - repository:
      owner: nais
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_PUSH_TOKEN }}"
    name: nais
    homepage: "https://github.com/nais/cli"
    description: "Command-line interface for NAIS"
    directory: Formula
    install: |-
      bin.install "nais"
      bash_completion.install "completions/nais.bash" => "nais"
      zsh_completion.install "completions/nais.zsh" => "_nais"
      fish_completion.install "completions/nais.fish"
    test: |
      assert_match version, shell_output("#{bin}/nais version")

nfpms:
  - package_name: nais
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    vendor: Nav / Nais team
    homepage: "https://github.com/nais/cli"
    maintainer: Nav / Nais team
    description: "Command-line interface for Nais"
    license: MIT
    formats:
      - deb
    version_metadata: git
    contents:
      - src: ./completions/nais.bash
        dst: /usr/share/bash-completion/completions/nais
        file_info:
          mode: 0644
      - src: ./completions/nais.fish
        dst: /usr/share/fish/vendor_completions.d/nais.fish
        file_info:
          mode: 0644
      - src: ./completions/nais.zsh
        dst: /usr/share/zsh/vendor-completions/_nais
        file_info:
          mode: 0644

scoops:
  - repository:
      owner: nais
      name: scoop-bucket
      token: "{{ .Env.SCOOP_PUSH_TOKEN }}"
    homepage: "https://github.com/nais/cli"
    description: "Command-line interface for NAIS"
    license: MIT
