[tasks.check]
description = "Run all static analysis tools"
depends = ['staticcheck','vulncheck','deadcode','vet']

[tasks.staticcheck]
description = "Run staticcheck"
wait_for = ['fmt']
run = "make staticcheck"

[tasks.vulncheck]
description = "Run govulncheck"
wait_for = ['fmt']
run = "make govulncheck"

[tasks.deadcode]
description = "Run deadcode"
wait_for = ['fmt']
run = "make deadcode"

[tasks.gosec]
description = "Run gosec"
wait_for = ['fmt']
run = "make gosec"

[tasks.vet]
description = "Run go vet"
wait_for = ['fmt']
run = "make vet"

[tasks.test]
description = "Run tests"
wait_for = ['fmt']
run = "make test"

[tasks.fmt]
description = "Format all go code using gofumpt"
run = "make fmt"

[tasks.build]
description = "Build the Nais CLI binary"
wait_for = ['fmt']
run = "make build"

[tasks.all]
description = "Run all tasks"
depends = ['fmt', 'check', 'test', 'build']

[settings]
pin = true

[tools]
go = "1.24.2"
