[tasks.check]
depends = ['staticcheck','vulncheck','deadcode','vet']

[tasks.staticcheck]
wait_for = ['fmt']
run = "go tool honnef.co/go/tools/cmd/staticcheck ./..."

[tasks.vulncheck]
wait_for = ['fmt']
run = "go tool golang.org/x/vuln/cmd/govulncheck ./..."

[tasks.deadcode]
wait_for = ['fmt']
run = "go tool golang.org/x/tools/cmd/deadcode -test ./..."

[tasks.gosec]
wait_for = ['fmt']
run = "go tool github.com/securego/gosec/v2/cmd/gosec --exclude-generated -terse ./..."

[tasks.vet]
wait_for = ['fmt']
run = "go vet ./..."

[tasks.test]
wait_for = ['fmt']
run = "go tool github.com/onsi/ginkgo/v2/ginkgo -r --race --randomize-all --randomize-suites --fail-on-pending --fail-on-empty"

[tasks.test-ci]
wait_for = ['fmt']
run = "go tool github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --fail-on-pending --fail-on-empty --keep-going --cover --coverprofile=cover.out --race --trace --junit-report=report.xml --github-output"

[tasks.fmt]
run = "go tool mvdan.cc/gofumpt -w ./"

[tasks.build]
wait_for = ['fmt']
run = "go build -installsuffix cgo -o bin/nais ./"

[tasks.all]
depends = ['fmt', 'check', 'test', 'build']

[settings]
pin = true

[tools]
go = "1.24.2"
