[tasks.check]
description = "Run all static analysis tools"
depends = ['staticcheck', 'vulncheck', 'deadcode', 'vet']

[tasks.staticcheck]
description = "Run staticcheck"
wait_for = ['fmt']
run = "go tool honnef.co/go/tools/cmd/staticcheck ./..."

[tasks.vulncheck]
description = "Run govulncheck"
wait_for = ['fmt']
run = "go tool golang.org/x/vuln/cmd/govulncheck -show verbose ./..."

[tasks.deadcode]
description = "Run deadcode"
wait_for = ['fmt']
run = "go tool golang.org/x/tools/cmd/deadcode -test ./..."

[tasks.gosec]
description = "Run gosec"
wait_for = ['fmt']
run = "go tool github.com/securego/gosec/v2/cmd/gosec --exclude-generated -terse ./..."

[tasks.vet]
description = "Run go vet"
wait_for = ['fmt']
run = "go vet ./..."

[tasks.test]
wait_for = ['fmt']
description = "Run tests"
run = "go tool github.com/onsi/ginkgo/v2/ginkgo -r --race --randomize-all --randomize-suites --fail-on-pending --fail-on-empty --keep-going --cover --coverprofile=cover.out --trace --junit-report=report.xml --github-output"

[tasks.fmt]
description = "Format all go code using gofumpt"
run = "go tool mvdan.cc/gofumpt -w ./"

[tasks.ci-fmt]
description = "Format all go code using gofumpt"
run = """
if ! go tool mvdan.cc/gofumpt -w ./; then
  echo 'Failed to run `mise fmt`.'
	exit 1
fi

if ! git diff --exit-code --name-only; then
  echo 'The file(s) listed above are not formatted correctly. Please run `mise fmt` and commit the changes.'
  exit 1
fi
"""

[tasks.build]
description = "Build the Nais CLI binary"
wait_for = ['fmt']
run = "go build -installsuffix cgo -o bin/nais ./"

[tasks.generate]
description = "Generate GraphQL client code"
run = "go tool github.com/Khan/genqlient"

[tasks.all]
description = "Run all tasks"
depends = ['generate', 'fmt', 'check', 'test', 'build']

[settings]
pin = true

[tools]
go = "1.24.4"
goreleaser = "2.9.0"
