#:schema ./schema.json

naisVersion = "v3"
environment = "dev-gcp"
team = "basseng"

[valkey.24s]
size = "LARGE"
maxMemoryPolicy = "ALLKEYS_LRU"

# alternatively
[openSearch.asdf]
size = "SMALL"

[openSearch.foo]
size = "MEDIUM"

[openSearch.bar]
size = "LARGE"
