# typed: false
# frozen_string_literal: true

# This file was generated by nais/cli. DO NOT EDIT.
class Nais < Formula

  desc "Command-line interface for NAIS"
  homepage "https://github.com/nais/cli"
  version "__VERSION__"
  version_scheme 1

  on_macos do
    on_intel do
      url "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___darwin_amd64.tar.gz"
      sha256 "__SHA_DARWIN_AMD64__"
    end
    on_arm do
      url "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___darwin_arm64.tar.gz"
      sha256 "__SHA_DARWIN_ARM64__"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___linux_amd64.tar.gz"
      sha256 "__SHA_LINUX_AMD64__"
    end
    on_arm do
      url "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___linux_arm64.tar.gz"
      sha256 "__SHA_LINUX_ARM64__"
    end
  end

  def install
    bin.install "nais"
  end

  test do
    assert_match version, shell_output("#{bin}/nais version")
  end

  livecheck do
    url "https://github.com/nais/cli.git"
    regex(/^v(\d+\.\d+\.\d+-\d{14}-[a-f0-9]{12})$/i)
  end
end
