# typed: false
# frozen_string_literal: true

# This file was generated by nais/cli. DO NOT EDIT.
class Nais < Formula
  desc "Command-line interface for Nais"
  homepage "https://github.com/nais/cli"
  version "$VERSION"
  version_scheme 1

  if OS.mac? do
    if Hardware::CPU.intel? do
      url "$NAIS_CLI_DARWIN_AMD64_URL"
      sha256 "$NAIS_CLI_DARWIN_AMD64_HASH_BASE16"

      def install
        bin.install "nais"
      end
    end
    if Hardware::CPU.arm? do
      url "$NAIS_CLI_DARWIN_ARM64_URL"
      sha256 "$NAIS_CLI_DARWIN_ARM64_HASH_BASE16"

      def install
        bin.install "nais"
      end
    end
  end

  if OS.linux? do
    if Hardware::CPU.intel? do
      url "$NAIS_CLI_LINUX_AMD64_URL"
      sha256 "$NAIS_CLI_LINUX_AMD64_HASH_BASE16"

      def install
        bin.install "nais"
      end
    end
    if Hardware::CPU.arm? do
      url "$NAIS_CLI_LINUX_ARM64_URL"
      sha256 "$NAIS_CLI_LINUX_ARM64_HASH_BASE16"

      def install
        bin.install "nais"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/nais version")
  end

  livecheck do
    url "https://github.com/nais/cli.git"
    regex(/^v(\d+\.\d+\.\d+-\d{14}-[a-f0-9]{12})$/i)
  end
end
