# typed: false
# frozen_string_literal: true

# This file was generated by nais/cli. DO NOT EDIT.
class Nais < Formula

  desc "Command-line interface for Nais"
  homepage "https://github.com/nais/cli"
  version "$VERSION"
  version_scheme 1

  on_macos do
    on_intel do
      url "$NAIS_CLI_DARWIN_AMD64_URL"
      sha256 "$NAIS_CLI_DARWIN_AMD64_HASH_BASE16"
    end
    on_arm do
      url "$NAIS_CLI_DARWIN_ARM64_URL"
      sha256 "$NAIS_CLI_DARWIN_ARM64_HASH_BASE16"
    end
  end

  on_linux do
    on_intel do
      url "$NAIS_CLI_LINUX_AMD64_URL"
      sha256 "$NAIS_CLI_LINUX_AMD64_HASH_BASE16"
    end
    on_arm do
      url "$NAIS_CLI_LINUX_ARM64_URL"
      sha256 "$NAIS_CLI_LINUX_ARM64_HASH_BASE16"
    end
  end

  def install
    bin.install "nais"
  end

  test do
    assert_match version, shell_output("#{bin}/nais version")
  end
end
