# This file was generated by nais/cli. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "$NAIS_CLI_LINUX_AMD64_HASH_BASE32";
    aarch64-linux = "$NAIS_CLI_LINUX_ARM64_HASH_BASE32";
    x86_64-darwin = "$NAIS_CLI_DARWIN_AMD64_HASH_BASE32";
    aarch64-darwin = "$NAIS_CLI_DARWIN_ARM64_HASH_BASE32";
  };

  urlMap = {
    x86_64-linux = "$NAIS_CLI_LINUX_AMD64_URL";
    aarch64-linux = "$NAIS_CLI_LINUX_ARM64_URL";
    x86_64-darwin = "$NAIS_CLI_DARWIN_AMD64_URL";
    aarch64-darwin = "$NAIS_CLI_DARWIN_ARM64_URL";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "nais-cli";
    version = "$VERSION";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./nais $out/bin/nais
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
