# This file was generated by nais/cli. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  shaMap = {
    x86_64-linux = "__SHA_LINUX_AMD64__";
    aarch64-linux = "__SHA_LINUX_ARM64__";
    x86_64-darwin = "__SHA_DARWIN_AMD64__";
    aarch64-darwin = "__SHA_DARWIN_ARM64__";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/nais/cli/releases/download/__VERSION__/nais-cli___VERSION___darwin_arm64.tar.gz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "nais-cli";
    version = "__VERSION__";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./nais $out/bin/nais
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
