@startuml
title nais-d

actor developer as "Developer"
control cli as "Cli"
control kubernetes as "Kubernetes"
control aivenator as "Aivenator"
control kafkarator as "Kafkarator"
boundary aiven as "Aiven"

developer -> cli : nais-d aiven my-user my-team
cli -> kubernetes : add or update

loop aivenator until success
kubernetes -> aivenator : Protected AivenApplication resource created/updated
aivenator -> aiven : Create or update serviceuser and credentials
aivenator -> kubernetes : Create secret
aivenator -> kubernetes : Write back status and sync hash
group Time limit exceeded
aivenator -> kubernetes : Delete Secret
kubernetes -> aivenator : AivenApplication Secret resource deleted
aivenator -> aiven : Delete serviceuser and credentials
aivenator -> aivenator : aivenApplication scheduled for deletion
aivenator -> kubernetes : Delete aivenApplication
    end
end

loop kafkarator until success
kubernetes -> kafkarator : Topic resource created/updated
kafkarator -> aiven : Create or update topics
kafkarator -> aiven : Create and/or delete ACLs
kafkarator -> kubernetes : Write back status and sync hash
note right: RolloutComplete
end

developer -> cli : nais-d aiven get my-secret-name my-team
cli -> kubernetes : extract credentials
cli <- kubernetes : credentials
developer <- cli : save to current

@enduml