package cmd

const (
	AccessFlag            = "access"
	AllPrivs              = "all-privs"
	AppName               = "appname"
	CommitInformation     = "commit"
	ContextFlag           = "context"
	DatabaseFlag          = "database"
	Email                 = "email"
	ExpireFlag            = "expire"
	Extras                = "extras"
	Force                 = "force"
	HostFlag              = "host"
	IncludeManagementFlag = "include-management"
	InstanceFlag          = "instance"
	NamespaceFlag         = "namespace"
	PoolFlag              = "pool"
	PortFlag              = "port"
	PrivilegeFlag         = "privilege"
	SecretNameFlag        = "secret-name"
	ServiceFlag           = "service"
	TeamName              = "teamname"
	TenantFlag            = "tenant"
	Topics                = "topics"
	UsernameFlag          = "username"
	VerboseFlag           = "verbose"
	AppPortFlag           = "appListenPort"
)
