package cmd

const (
	AccessFlag        = "access"
	AppName           = "appname"
	CommitInformation = "commit"
	ContextFlag       = "context"
	Email             = "email"
	ExpireFlag        = "expire"
	Extras            = "extras"
	Force             = "force"
	HostFlag          = "host"
	InstanceFlag      = "instance"
	NamespaceFlag     = "namespace"
	PoolFlag          = "pool"
	PortFlag          = "port"
	PrivilegeFlag     = "privilege"
	SecretNameFlag    = "secret-name"
	ServiceFlag       = "service"
	TeamName          = "teamname"
	TenantFlag        = "tenant"
	Topics            = "topics"
	UsernameFlag      = "username"
	VerboseFlag       = "verbose"
)
